Repository OpenShopChannel/Apps, pull requests merged in 2024-08, with the labels that each got.

#80 Add GRRLIB Examples Collection
  contents/GRRLIB-Examples-Collection.oscmeta
Labels: new app

#78 Add Wiilink WFC Patcher
  contents/WiiLink WFC Patcher.oscmeta
Labels: awaiting response

#86 found actual repository for brainslug.oscmeta
  contents/brainslug.oscmeta
Labels: app source
