Repository OpenShopChannel/Apps, pull requests merged in 2024-03, with the labels that each got.

#52 Add wii-screen
  contents/wii-screen.oscmeta
Labels: new app, good first issue

#53 Add VVVVVV
  contents/VVVVVV.oscmeta
Labels: new app

#59 Update to version 0.0.2
  contents/CookwiiClicker.oscmeta
Labels: app update
